name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run server
        run: |
          php -S localhost:8080 -t tests/fixtures/www &> /dev/null & 
#          java -jar selenium.jar &> /dev/null &

      - name: Run tests
        run: bin/behat -fprogress --tags="~@user&&~@skip&&~@javascript"

#          apk update &&
#          apk add chromium-chromedriver \
#          openjdk10-jre
#          wget "https://selenium-release.storage.googleapis.com/3.9/selenium-server-standalone-3.9.1.jar" -O selenium.jar
#          php -S localhost:8080 -t tests/fixtures/www &> /dev/null &
#          java -jar selenium.jar &> /dev/null &
#          bin/behat -fprogress --tags="~@user&&@~skip"
# Works great with openjdk10-jre